language: node_js
node_js:
  - 12

services:
  - docker

#Pre-testing installs
install:
  - echo "nothing needs to be installed"

#Scripts to run such as tests
before_script:
  - echo "no tests. But there will be"

script:
  - docker --version #print the version for logging here.
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  #Tagging
  - docker tag udagram-api-feed mostafaelbeih1995/udagram-api-feed:v6
  - docker tag udagram-api-user mostafaelbeih1995/udagram-api-user:v6
  - docker tag udagram-frontend mostafaelbeih1995/udagram-frontend:v6
  - docker tag udagram-reverseproxy mostafaelbeih1995/reverseproxy:v6

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mostafaelbeih1995/udagram-api-feed:v6
  - docker push mostafaelbeih1995/udagram-api-user:v6
  - docker push mostafaelbeih1995/udagram-frontend:local
  - docker push mostafaelbeih1995/reverseproxy:v6